# Generated by Django 2.1.4 on 2018-12-13 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20181204_0218'),
        ('articles', '0003_auto_20181211_1244'),
    ]

    operations = [
    ]
